#XXX-XX Created index file
AgileCyberSolutions/PR-Repo pull request #1
Opened 2023-03-14 04:54 UTC by Ayyappan-RK

2023-03-14 05:02 UTC, AgileCyberSolutions requested changes

2023-03-14 05:02 UTC, AgileCyberSolutions commented on index.html
> +    Index
There is no comments in the html file. Please add comments and commit it again

2023-03-14 05:55 UTC, Ayyappan-RK commented on index.html
> +    Index
Added. please check and merge my request

2023-03-14 05:56 UTC, AgileCyberSolutions approved these changes

2023-03-14 09:23 UTC, merged

2023-03-15 12:33 UTC, Ayyappan-RK commented
@AgileCyberSolutions Please review